import Head from "next/head";
import Link from "next/link";
// import PostList from "../components/posts/PostList";
import Parent from "../components/children/Parent";
import Child from "../components/children/Child";
import SecondChild from "~/components/children/SecondChild";
import Events from "../components/events/Events";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-20">
        <h1 className="mb-4 text-3xl">lama dev typescript react tutorial</h1>

        <Events />

        {/* <PostList /> */}
        <br></br>

        {/* <Parent>
        <Child />
        <hr></hr>
        <SecondChild />
      </Parent> */}
        <br></br>
      </div>
    </>
  );
}
