import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import PostList from "../components/posts/PostList";
import Parent from "../components/children/Parent";
import Child from "../components/children/Child";
import SecondChild from "~/components/children/SecondChild";
import Events from "../components/events/Events";
import StateExample from "../components/state/StateExample";

export default function Home() {
  const [showEvents, setShowEvents] = useState(false);
  const [showPosts, setShowPosts] = useState(false);
  const [showParentChild, setShowParentChild] = useState(false);
  const [showState, setShowState] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-20">
        <h1 className="mb-4 text-3xl">lama dev ts-react tutorial</h1>
        <div className="mb-10 flex flex-row gap-4">
          <button
            className="rounded-xl bg-green-500 p-2"
            onClick={() => setShowEvents(!showEvents)}
          >
            Events
          </button>
          <button
            className="rounded-xl bg-green-500 p-2"
            onClick={() => setShowPosts(!showPosts)}
          >
            Posts
          </button>
          <button
            className="rounded-xl bg-green-500 p-2"
            onClick={() => setShowParentChild(!showParentChild)}
          >
            Parent/Child
          </button>
          <button
            className="rounded-xl bg-green-500 p-2"
            onClick={() => setShowState(!showState)}
          >
            State
          </button>
        </div>

        {showEvents && <Events />}

        {showPosts && <PostList />}

        {showParentChild && (
          <Parent>
            <Child />
            <hr></hr>
            <SecondChild />
          </Parent>
        )}

        {showState && <StateExample />}
      </div>
    </>
  );
}
